steps:
  # FRONTEND STEPS
  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]

  # Build settings.json file from Subsitution variable _SETTINGS_JSON which contains
  # the environment's values for the settings.json file.
  - name: 'ubuntu'
    args: [ 'bash', './build-settings-json.sh', '$_SETTINGS_JSON' ]

  # # Verify settings.json file
  # - name: 'ubuntu'
  #   args: [ 'tail', './settings.json' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '240s'
  
timeout: 5m